export const routes = {
  login: '/login',
  signup: '/signup',
  signupInfo: '/signup/info',
  home: '/home',
  reportRecord: '/reports/record',
  reportUploading: '/reports/uploading',
  reportTranscription: '/reports/transcription',
  reportPlace: '/reports/place',
  reportConfirm: '/reports/confirm',
  reportDrafts: '/reports/drafts',
  myReports: '/reports/mine',
  guidancePreview: '/guidance/preview',
  guidanceStep: '/guidance/step',
  guidanceCompleted: '/guidance/completed',
  guidanceUnavailable: '/guidance/unavailable',
  admin: '/admin',
  adminReviews: '/admin/reviews',
  adminPlaces: '/admin/places',
  adminRoutes: '/admin/routes',
  adminKnowledge: '/admin/routes/knowledge',
  adminValidation: '/admin/routes/validation',
} as const
